apiPort: 12000
logLevel: info
source:
  root: "./root"
  concurrentSenders: 20
  pollIntervalSeconds: 1
  bucketType: "minio"
  bucketName: "bucket"
target:
  address: "localhost:50000"
  queue: q1
  clientId: ""
  authToken: ""
