# github.com/go-task/task

version: '3'

vars:
  BINARY_NAME: file-uploader
  VERSION: v1.0.0

tasks:
  default:
    cmds:
      - go run . --config ./config.yaml
  check_update:
    cmds:
      - go list -u -m -json -mod=mod all | go-mod-outdated -update -direct
  lint:
    cmds:
      - golangci-lint run --disable gocritic --enable misspell
  test:
    cmds:
      - go test -timeout 30m ./...
  build:
    env:
      GOOS: '{{OS}}'
      GOARCH: '{{ARCH}}'
    cmds:
      - go mod tidy
      - go mod vendor
      - go build -buildmode=exe -o "{{.BINARY_NAME}}.exe" -ldflags "-X main.version={{.VERSION}}"
  commit-modifed:
    cmds:
      - git add -A
      - git commit -a -m "release {{.VERSION}}"
      - git push origin main
  tag:
    cmds:
      - git tag -a {{.VERSION}} -m {{.VERSION}}
      - git push origin main --tags
  release:
    cmds:
      - go mod vendor
      - task: lint
      - task: commit-modifed
      - task: docker
      - task: push
      - task: tag
